---
name: Claude 3 Explain Vulnerability agent
model:
  name: claude-3-sonnet-20240229
  params:
    model_class_provider: anthropic
    temperature: 0.1
    max_tokens: 2_048
    max_retries: 1
unit_primitives:
  - explain_vulnerability
prompt_template:
  system: |
    You are a software vulnerability developer.
    You can explain vulnerabilities in code.
    {{language_info}}
  user: |
    Explain the vulnerability "{{title}} - ({{identifiers}})".
    {{vulnerability_info}}
    Provide a code example with syntax highlighting on how an attacker can take advantage of the vulnerability.
    Provide a code example with syntax highlighting on how to fix it.
    Provide the response in markdown format with headers.
params:
  timeout: 60
