apiVersion: batch/v1
kind: Job
metadata:
  name: model-loader-job
  labels:
    {{- include "ai-assist.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: model-loader
          image: {{ .Values.modelLoaderJob.modelLoader.image.repository }}:{{ .Values.modelLoaderJob.modelLoader.image.tag | default .Chart.AppVersion }}
          env:
            - name: MODELS_DIR
              value: {{ quote .Values.modelLoaderJob.modelLoader.env.modelsDir }}
            - name: MODEL_FT_CONFIG
              value: {{ quote .Values.modelLoaderJob.modelLoader.env.modelFtConfig }}
          command: [ "/bin/sh", "-c", "--" ]
          args:
            - rm -rf $(MODELS_DIR) && mkdir -p $(MODELS_DIR);
              cp -r /model/* $(MODELS_DIR);
              sed -e 's@${MODELS_DIR}@'"$MODELS_DIR"'@' -e 's@${MODEL_NUM_GPU}@'"$MODEL_NUM_GPUS"'@' $(MODEL_FT_CONFIG) > $(MODEL_FT_CONFIG).tmp;
              mv $(MODEL_FT_CONFIG).tmp $(MODEL_FT_CONFIG);
              curl -L "${MODEL_ARCHIVE}" -o /data/model.tar.zst;
              zstd -dc /data/model.tar.zst | tar -xf - -C "${MODELS_DIR}" --strip-components=1;
              rm -f /data/model.tar.zst;
          volumeMounts:
            - name: models-fauxpilot-nfc-pvc-volume
              mountPath: /data
      volumes:
        - name: models-fauxpilot-nfc-pvc-volume
          persistentVolumeClaim:
            claimName: models-fauxpilot-nfs-pvc
      restartPolicy: Never
