FROM alpine:3.17.0

ARG MODEL_ID="codegen"
ARG MODEL_VERSION="1"
ARG MODEL_NAME="Salesforce/codegen-350M-multi"
ARG MODEL_DIR="/model/${MODEL_ID}"
ARG MODEL_HF_REPO="https://huggingface.co/${MODEL_NAME}"

ENV MODEL_HF_REPO=${MODEL_HF_REPO}
ENV MODEL_HF_CACHE="/hf/${MODEL_ID}"

RUN apk add --no-cache git git-lfs

RUN mkdir -p ${MODEL_DIR}/${MODEL_VERSION}
WORKDIR ${MODEL_DIR}

COPY config.pbtxt .
COPY model.py ${MODEL_VERSION}/.

ENTRYPOINT ["sh", "-c"]