name: "preprocessing"
backend: "python"
max_batch_size: 128
dynamic_batching {
  max_queue_delay_microseconds: 350000
}

input [
    {
        name: "PROMPT"
        data_type: TYPE_STRING
        dims: [ -1 ]
    },
    {
        name: "REQUEST_OUTPUT_LEN"
        data_type: TYPE_UINT32
        dims: [ -1 ]
    }
]
output [
    {
        name: "INPUT_IDS"
        data_type: TYPE_UINT32
        dims: [ -1 ]
    },
    {
        name: "REQUEST_INPUT_LEN"
        data_type: TYPE_UINT32
        dims: [ 1 ]
    },
    {
        name: "REQUEST_OUTPUT_LEN"
        data_type: TYPE_UINT32
        dims: [ -1 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]