FROM nvcr.io/nvidia/tritonserver:22.11-pyt-python-py3

RUN pip install --no-cache-dir \
                            torch==1.13.0 \
                            accelerate==0.15.0 \
                            transformers==4.25.1
